### ISSUE TITLE
Performance von sizeWithoutNulls

### ISSUE THREAD

**Issue by stefanmuenchow** [stefanmuenchow/Smart-Collections#2]
In der Listenimplementierung ist eine sehr unvorteilhafte Implementierung von sizeWithoutNulls enthalten. Diese entsprechend optimieren.

**Comment by alexanderbartels** [comment]
Habs geändert, aber mein git will das nicht committen.
Wen du mir sagst wie würde ich das tun.

**Comment by stefanmuenchow** [comment]
Versuchs nochmal, ich hab dich mal als Collaborator eingetragen. Falls es immer noch nicht klappt, dann poste mal die Fehlermeldung.

**Comment by stefanmuenchow** [comment]
Erledigt.
