### ISSUE TITLE
toList() und mapToList(...) in SmartList Interface

### ISSUE THREAD

**Issue by alexanderbartels** [stefanmuenchow/Smart-Collections#3]
Es fehlt eine Methode im SmartList Interface die es ermöglicht die SmartList in eine Standard liste vom Java Collection Framework zu konvertieren. 
Also die SmartArrayList sollte eine ArrayListe zurückgeben und die SmartLinkedList eine LinkedList usw. ...

Außerdem wäre eine Methode wünschenswert die beim Konvertieren der Liste auch die Objekte mappen kann.

**Comment by stefanmuenchow** [comment]
Neue Methode toStandardCollection() bzw. toStandardMap in allen Typen hinzugefügt. Eine Map-Operation, die direkt eine Standard-Collection erzeugt, ist nicht erforderlich, da toStandardCollection() nur die intern verwendete Collection zurückgibt, anstatt eine neue zu erzeugen. Es ist also genauso performant

coll.map()....toStandardCollection()

zu verwenden.
